#! /usr/bin/env python
# encoding: utf-8
#
# Altruistic Control Systems
# Control Node base wscript
# Kenneth Wells, 2015

from waflib import Options, Logs
from waflib import Configure

def configure(conf):
    pass

def build(bld):
    pass
