#! /usr/bin/env python
# encoding: utf-8
#
# Altruistic Control Systems
# Control Node base wscript
# Kenneth Wells, 2015

from waflib import Options, Logs
from waflib import Configure

def configure(conf):
    pass

def build(bld):

    bld(
        install_path='${PREFIX}/bin',
        manifest='node.package',
        target='node',
        features=['cxx', 'cxxprogram','package', 'qt5'],
        uselib=['QTCORE','QTGUI','QTOPENGL','QTSVG','QTDBUS']
        )

    if bld.env.UNIT_TESTS:
        bld.recurse('unitTests')

    if bld.env.SMOKE_TESTS:
        bld.recurse('smokeTests')
